package com.valueinvesting.webapp.fmp.dto

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

// FMP Key Metrics DTO — nullable-aware per US-004 AC.
// [^src: design_&_architecture/decisions/ADR-004-fmp-integration.md §Adapter pattern]
// [^src: wiki/concepts/fmp-metrics-ratios.md §Key Metrics]
@JsonIgnoreProperties(ignoreUnknown = true)
data class KeyMetricsDto(
    val symbol: String? = null,
    val date: String? = null,
    val calendarYear: String? = null,
    val period: String? = null,
    val revenuePerShare: Double? = null,
    val netIncomePerShare: Double? = null,
    val operatingCashFlowPerShare: Double? = null,
    val freeCashFlowPerShare: Double? = null,
    val cashPerShare: Double? = null,
    val bookValuePerShare: Double? = null,
    val tangibleBookValuePerShare: Double? = null,
    val shareholdersEquityPerShare: Double? = null,
    val interestDebtPerShare: Double? = null,
    val marketCap: Double? = null,
    val enterpriseValue: Double? = null,
    val peRatio: Double? = null,
    val priceToSalesRatio: Double? = null,
    val pocfratio: Double? = null,
    val pfcfRatio: Double? = null,
    val pbRatio: Double? = null,
    val ptbRatio: Double? = null,
    val evToSales: Double? = null,
    val enterpriseValueOverEBITDA: Double? = null,
    val evToOperatingCashFlow: Double? = null,
    val evToFreeCashFlow: Double? = null,
    val earningsYield: Double? = null,
    val freeCashFlowYield: Double? = null,
    val debtToEquity: Double? = null,
    val debtToAssets: Double? = null,
    val netDebtToEBITDA: Double? = null,
    val currentRatio: Double? = null,
    val interestCoverage: Double? = null,
    val incomeQuality: Double? = null,
    val dividendYield: Double? = null,
    val payoutRatio: Double? = null,
    val salesGeneralAndAdministrativeToRevenue: Double? = null,
    val researchAndDdevelopementToRevenue: Double? = null,
    val intangiblesToTotalAssets: Double? = null,
    val capexToOperatingCashFlow: Double? = null,
    val capexToRevenue: Double? = null,
    val capexToDepreciation: Double? = null,
    val stockBasedCompensationToRevenue: Double? = null,
    val grahamNumber: Double? = null,
    val roic: Double? = null,
    val returnOnTangibleAssets: Double? = null,
    val grahamNetNet: Double? = null,
    val workingCapital: Double? = null,
    val tangibleAssetValue: Double? = null,
    val netCurrentAssetValue: Double? = null,
    val investedCapital: Double? = null,
    val averageReceivables: Double? = null,
    val averagePayables: Double? = null,
    val averageInventory: Double? = null,
    val daysSalesOutstanding: Double? = null,
    val daysPayablesOutstanding: Double? = null,
    val daysOfInventoryOnHand: Double? = null,
    val receivablesTurnover: Double? = null,
    val payablesTurnover: Double? = null,
    val inventoryTurnover: Double? = null,
    val roe: Double? = null,
    val capexPerShare: Double? = null,
)
